### PR TITLE
Travis CI & PHPUnit Watcher

### PR DESCRIPTION
**Pull request by veerajongit**
CI added with test coverage

### CODE REVIEW

**Comment by r-brown** [comment]
MySQL issue fix decribed here: https://github.com/travis-ci/travis-ci/issues/6842

**Comment by veerajongit** [comment]
> MySQL issue fix decribed here: [travis-ci/travis-ci#6842](https://github.com/travis-ci/travis-ci/issues/6842)

I don't get you, there is no mysql error to this commit.

**Comment by r-brown** [comment]
@veerajongit no worries - you implicitly fixed this with this https://github.com/Labs64/laravel-boilerplate/pull/65/commits/06785285636c7718a30bacc78bd075597bc68bc7#diff-354f30a63fb0907d4ad57269548329e3R5

My comment intention was only to keep others informed. Thank you!

**Comment by r-brown** [comment]
@veerajongit I see some new attributes in the `.env.travis` have been introduced

```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}" 
```

Any idea how to use these? Is some external service expected here to be used?

**Comment by veerajongit** [comment]
Those are if you wish to use Pusher or AWS services.

**Comment by veerajongit** [comment]
Unnecessary for travis

**Pull request merged**
